"""Adicionando novas colunas de data e hora

Revision ID: dfcc404e2c29
Revises: 
Create Date: 2024-07-26 02:26:32.428206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfcc404e2c29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dreams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dream_datetime', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('date_modified', sa.DateTime(), nullable=False))
        batch_op.drop_column('date')
        batch_op.drop_column('time')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('user_email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('user_pwd_hash', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('date_modified', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint('_user_email_uc', ['user_email'])
        batch_op.create_index(batch_op.f('ix_users_user_email'), ['user_email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_email'))
        batch_op.drop_constraint('_user_email_uc', type_='unique')
        batch_op.drop_column('date_modified')
        batch_op.drop_column('date_created')
        batch_op.drop_column('user_pwd_hash')
        batch_op.drop_column('user_email')
        batch_op.drop_column('user_name')

    with op.batch_alter_table('dreams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=5), nullable=False))
        batch_op.add_column(sa.Column('date', sa.VARCHAR(length=8), nullable=False))
        batch_op.drop_column('date_modified')
        batch_op.drop_column('date_created')
        batch_op.drop_column('dream_datetime')

    # ### end Alembic commands ###
